// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe70KaDAHQLUJfjAVTcJHIrpq_jSY7bLw',
    appId: '1:682276065096:web:41169ee820039bd5b06d7d',
    messagingSenderId: '682276065096',
    projectId: 'new-care-b25a1',
    authDomain: 'new-care-b25a1.firebaseapp.com',
    storageBucket: 'new-care-b25a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkq2o26Hee0043H8ns_fl-NYXhsbclMkU',
    appId: '1:682276065096:android:2dfa93add8d49f1fb06d7d',
    messagingSenderId: '682276065096',
    projectId: 'new-care-b25a1',
    storageBucket: 'new-care-b25a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2i8TiZJTU6pJPhj2qxaxMIIFfUufBWHs',
    appId: '1:682276065096:ios:0676632e96e8f477b06d7d',
    messagingSenderId: '682276065096',
    projectId: 'new-care-b25a1',
    storageBucket: 'new-care-b25a1.firebasestorage.app',
    iosBundleId: 'com.example.newCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2i8TiZJTU6pJPhj2qxaxMIIFfUufBWHs',
    appId: '1:682276065096:ios:0676632e96e8f477b06d7d',
    messagingSenderId: '682276065096',
    projectId: 'new-care-b25a1',
    storageBucket: 'new-care-b25a1.firebasestorage.app',
    iosBundleId: 'com.example.newCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe70KaDAHQLUJfjAVTcJHIrpq_jSY7bLw',
    appId: '1:682276065096:web:950efda4b3260da5b06d7d',
    messagingSenderId: '682276065096',
    projectId: 'new-care-b25a1',
    authDomain: 'new-care-b25a1.firebaseapp.com',
    storageBucket: 'new-care-b25a1.firebasestorage.app',
  );
}
